# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.7.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.5'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# postgres database
gem 'pg'

group :development do
  gem 'faraday'
  gem 'minitest', require: false
  gem 'rake', require: false
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
end
